### ISSUE TITLE
Defective button of "Not Interested" on PREMIER videos

### ISSUE THREAD

**Issue by binhnguyenvo** [lozog/not-interested-youtube#2]
I click on "Not Interested" button for a **Premier** video, but it shows "Not recommend this channel...."  (note: only Premier videos have this bug)  --> it may be that the extension confuses the function between these buttons.
Please refer to the attached image for more information.

+ Browser version: Firefox 130.0 (64-bit)
+ Browser Language: English (US)
+ Language identified and shown on Youtube: Vietnamese
+ Location (my country): Vietnam

![Bug 2](https://github.com/user-attachments/assets/a2152652-ff5a-4e51-afc1-0f5e8b5d04de)

**Comment by lozog** [comment]
@binhnguyenvo can you click on the 3 dots button on a Premier video and send a screenshot of what that menu looks like?

**Comment by binhnguyenvo** [comment]
Sure, here you are:

![Bug 4](https://github.com/user-attachments/assets/6f40fe04-8fed-4fac-90e1-5e1030b3f736)

**Comment by binhnguyenvo** [comment]
I also recorded a video of this PREMIER bug for premier videos (that is live broadcasting):

https://waaw.ac/f/sH7ITfHNEAx7

**Comment by lozog** [comment]
@binhnguyenvo can you confirm this behaviour is fixed as of version 1.3?

**Comment by binhnguyenvo** [comment]
Yes, it has been resolved as well in version 1.3.
Thanks for your effort.

**Comment by binhnguyenvo** [comment]
Hello, it would be good if you could remove all debugging information in the extension. Currently, some logs in Console window still remain.
