### ISSUE TITLE
Sometime the behavior of "Not interested" button becomes "Not recommend this channel" button

### ISSUE THREAD

**Issue by binhnguyenvo** [lozog/not-interested-youtube#3]
Sometime I click on "Not interested" button, but it shows "Not recommend this channel" button.
Especially, for **new channels** (that I have never seen before), this bug occurs very frequently.
Please refer to the attached image for more information.

+ Browser version: Firefox 130.0 (64-bit)
+ Browser Language: English (US)
+ Language identified and shown on Youtube: Vietnamese
+ Location (my country): Vietnam

![Bug 3](https://github.com/user-attachments/assets/c326d9b1-9a71-4497-a19d-85aa812bd3d3)

**Comment by lozog** [comment]
can you confirm that the correct button is being clicked? when you hover each of them, it will be highlighted. I'm wondering if it might be some sort of overlap issue.

**Comment by binhnguyenvo** [comment]
Yes, I'm absolutely sure that the position of mouse pointer is on the "Not interested" button. Additionally, then I clicked on "Cancel" button, and then re-clicked at the Thumb button again, but got the same wrong message "Not recommend this cannel". Please be noted that this frequently happens to NEW CHANNELS (that I have never seen that channel before). You can try that issue and be easy to see it.

**Comment by lozog** [comment]
@binhnguyenvo can you confirm this behaviour is fixed as of version 1.3?
